#!/bin/sh
#
# Hikari Support script for macOS.
# Add its directory to $PATH.
#
SCRIPT_DIR="$( cd "$( dirname "$0" )" && pwd )"

# Target triplet
PREFIX_CC=/usr/bin/

CPP=no

case "$0" in
    *++) CPP="yes" ;;
esac

if [ "${CPP}" = "yes" ]; then
   	CLANG="clang++"
else
	CLANG="clang"
fi

exec ${PREFIX_CC}${CLANG} ${ARGS} "$@" 
